name: Update IBDB
on:
  schedule:
    - cron:  '0 5,11,17,22 * * *'

  workflow_dispatch:

jobs:
  update-ibdb:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          # Maps tcp port 5432 on service container to the host
          - 54320:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Install postgres deps
        run: |
          sudo apt-get remove --purge -y postgresql-13
          sudo apt-get install -y postgresql-client-12

      - name: Init postgres db
        run: |
          PGPASSWORD=postgres psql -h localhost -p 54320 -U postgres -f ibdb/db_dump.sql

      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update IBDB
        env:
          TZ: America/New_York
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOSTNAME: localhost
          POSTGRES_PORT: 54320
        run: |
          python ibdb/api.py &
          sleep 5
          python ibdb/populate_db.py
          bash ./update.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Updating IBDB
          title: Updating IBDB
          body: |
            - IDBD updates
          branch: update-ibdb
